### ISSUE TITLE
Add Deck GCE predictive autoscaling to known issue - v2.22.0 Armory Release (OSS Spinnaker™ v1.22.1)

### ISSUE THREAD

**Issue by CB-GuangyaoXie** [armory/docs#243]
Hi folks,

We ran into this Deck issue when testing v2.22.0. https://github.com/spinnaker/deck/pull/8585#issuecomment-696330523
Please consider adding the fix to known issues.

**Comment by 317brian** [comment]
Thanks for opening this issue @CB-GuangyaoXie and bringing it to our attention. I"ll work on adding it today.

**Comment by 317brian** [comment]
Fixed by https://github.com/armory/docs/pull/248
