### ISSUE TITLE
Spinnaker GitOps with Halyard

### ISSUE THREAD

**Issue by shubhamc183** [armory/docs#308]
Couples of issues I have found while configuring GitOps with Halyard

- `run-halyard.sh`
	-  Run the `halyard` container in the background mode else it will be stuck forever in the `docker` run command.
		- docker run -**d** will help
	-  `HAL_HOME` which is being mounted inside the container should have 1000:1000 ownership i.e of spinnaker user inside halyard else it'll throw an error in creating `staging` directories.
		- `sudo chown -R 1000:1000 HAL_HOME` not sure if CI can be asked to do sudo command or should be asked in the first place.

```+ + Preparation complete... deploying Spinnaker  
+ Get current deployment  
Success  
- Apply deployment  
Failure  
Validation in Global:  
! ERROR Error creating the directory  
/home/spinnaker/.hal/default/staging: Error creating the directory  
/home/spinnaker/.hal/default/staging with unknown reason.  
  
- Failed to deploy Spinnaker.```

**Comment by aimeeu** [comment]
@shubhamc183 Thanks for creating this issue!
To confirm, the page you looking at is "Spinnaker GitOps with Halyard"  https://docs.armory.io/docs/armory-admin/halyard-gitops/

What versions of Armory and Armory Halyard are you using? 
What OS and version are you using?

**Comment by shubhamc183** [comment]
Yes, I am talking about "Spinnaker GitOps with Halyard" which is at https://docs.armory.io/docs/armory-admin/halyard-gitops/

Actually, I am using halyard from Spinnaker, not Armory nor Armory Halyard. I think maybe here I mixed them and eventually got confused.

Halyard: gcr.io/spinnaker-marketplace/halyard:1.40.0

**Comment by shubhamc183** [comment]
Closing this ticket due to inactivity.
