### ISSUE TITLE
cluster missing SpinnakerService.yml

### ISSUE THREAD

**Issue by ylohnitram** [armory/docs#326]
> If you installed Operator in cluster mode, run this command:
> 
> `kubectl -n spinnaker-operator apply -f deploy/spinnaker/cluster/SpinnakerService.yml`

--------------

The folder deploy/spinnaker/cluster doesn't exist!

**Comment by sh4sh** [comment]
Ah that filepath is supposed to be `deploy/spinnaker/kustomize/SpinnakerService.yml`.

So the full command is:
`kubectl -n spinnaker-operator apply -f deploy/spinnaker/kustomize/SpinnakerService.yml`
