### ISSUE TITLE
Configuring Gate and Deck to Run on the Same Hostname

### ISSUE THREAD

**Issue by IxDay** [armory/docs#341]
When reading the doc it seems that we are overriding some files in the Halyard approach section.

It states:
```bash
# Make the service-settings directory if it doesn't already exist

mkdir /home/spinnaker/.hal/default/service-settings

# Make the gate-local.yml file in the profile directory

tee /home/spinnaker/.hal/default/profiles/gate-local.yml <<-'EOF'
healthEndpoint: /api/v1/health
EOF
```

But this `/home/spinnaker/.hal/default/profiles/gate-local.yml` file has already been written by the previous command:

```bash
tee /home/spinnaker/.hal/default/profiles/gate-local.yml <<-'EOF'
server:
  servlet:
    context-path: /api/v1
EOF
```

**Comment by alexfornuto** [comment]
Hi @IxDay. I think you're right, but we can resolve by adding the `-a` flag to the second `tee` command, to append instead of overwriting. I'll make a patch.
