### ISSUE TITLE
PaCRD doc link produces 404

### ISSUE THREAD

**Issue by HawaiianSpork** [armory/docs#469]
The link from this page https://docs.armory.io/docs/spinnaker-user-guides/pacrd/ to https://docs.armory.io/docs/spinnaker-user-guides/pacrd-crd-docs/ produces a 404.

**Comment by aimeeu** [comment]
Thank you @HawaiianSpork for catching this. In addition to pushing a fix, I've created a task to change our link checker to one that compiles the site before checking.
